openapi: 3.0.3
info:
  title: Hello world
  description: Test application for sharing
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Localhost on port 8000
  - url: http://localhost:9000
    description: Localhost on port 9000
paths:
  /api/hello/{name}:
    get:
      tags:
        - HelloWorld
      description: Say hello to a name
      operationId: sayHello
      parameters:
        - name: name
          in: path
          description: Name to say hi to
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorld'
        '400':
          description: Invalid status value
components:
  schemas:
    HelloWorld:
      type: object
      properties:
        name:
          type: string